import { colors } from '@/theme/colors';
import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    position: 'relative',
  },
  decorCircleOrange: {
    position: 'absolute',
    top: -60,
    right: -60,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: colors.orangeTint,
    opacity: 0.6,
  },
  decorCircleTeal: {
    position: 'absolute',
    bottom: -80,
    left: -80,
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: colors.tealTint,
    opacity: 0.4,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 40,
  },
  innerContainer: {
    width: '100%',
    maxWidth: 380,
    alignItems: 'center',
  },
  iconOuterRing: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: colors.orangeTint,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
    position: 'relative',
    borderWidth: 2,
    borderColor: 'rgba(232, 92, 28, 0.15)',
  },
  iconInnerCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  statusBadge: {
    position: 'absolute',
    top: 2,
    right: 2,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#ef4444',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: colors.background,
  },
  textSection: {
    alignItems: 'center',
    marginBottom: 24,
    paddingHorizontal: 12,
  },
  headline: {
    fontFamily: 'Nunito_800ExtraBold',
    fontSize: 22,
    color: colors.textStrong,
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 15,
    color: colors.primary,
    textAlign: 'center',
    marginBottom: 10,
  },
  description: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 14,
    color: colors.textBody,
    textAlign: 'center',
    lineHeight: 20,
  },
  errorBox: {
    width: '100%',
    backgroundColor: '#fef2f2',
    borderRadius: 12,
    padding: 14,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.2)',
    textAlign: "center",
    display: "flex",
    alignItems: "center",
  },
  errorBoxHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  errorBoxLabel: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 12,
    color: '#b91c1c',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  errorBoxText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: '#7f1d1d',
    lineHeight: 18,
  },
  actionContainer: {
    width: '100%',
    alignItems: 'center',
  },
  retryButtonWrapper: {
    width: '100%',
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 12,
  },
  retryButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
  },
  retryButtonGradient: {
    flexDirection: 'row',
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 20,
  },
  retryButtonText: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 15,
    color: '#ffffff',
  },
  signOutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    height: 44,
    paddingHorizontal: 20,
    borderRadius: 10,
    marginBottom: 20,
  },
  signOutButtonPressed: {
    backgroundColor: colors.destructivePressedBg,
  },
  signOutButtonText: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 14,
    color: colors.textBody,
  },
  troubleshootText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: colors.textMutedDark,
    textAlign: 'center',
  },
  contactSupportLink: {
    fontFamily: 'Nunito_700Bold',
    color: colors.primary,
  },
});

export default styles;
